export const AUTH_FAIL = 'AUTH_FAIL',
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    AUTH_START = 'AUTH_START',
    REG_DOCTOR_START = 'REG_DOCTOR_START',
    REG_DOCTOR_EXIST = 'REG_DOCTOR_EXIST',
    REG_DOCTOR_SUCCESS = 'REG_DOCTOR_SUCCESS',
    REG_PATIENT_START = 'REG_PATIENT_START',
    REG_PATIENT_EXIST = 'REG_PATIENT_EXIST',
    REG_PATIENT_SUCCESS = 'REG_PATIENT_SUCCESS',
    RESET_REG_STATUS = 'RESET_REG_STATUS';

export const GET_PATIENT_DOCTORS = 'GET_PATIENT_DOCTORS',
    GET_PATIENT_DOCTORS_SHORT = 'GET_PATIENT_DOCTORS_SHORT',
    GET_PATIENT_DOCTORS_LOADING = 'GET_PATIENT_DOCTORS_LOADING',
    GET_NOT_PATIENT_DOCTORS = 'GET_NOT_PATIENT_DOCTORS',
    SELECT_STUDENT = 'SELECT_STUDENT',
    SET_RECEPTION = "SET_RECEPTION",
    GET_RESULTS_HEADER_SEARCH = 'GET_RESULTS_HEADER_SEARCH',
    GET_SELECTORS = 'GET_SELECTORS',
    GET_PROMO_LIST = 'GET_PROMO_LIST',
    GET_USER_COUNTRY = 'GET_USER_COUNTRY',
    GET_ABONEMENTS_PRICE = 'GET_ABONEMENTS_PRICE';

export const INFO_PATIENT = 'INFO_PATIENT';

export const INFO_DOCTOR = 'INFO_DOCTOR',
    TRAINER_TRAININGS = 'TRAINER_TRAININGS';

export const LOADING_START = 'LOADING_START',
    LOADING_END = 'LOADING_END',
    DOC_EMERGANCY_RECEIVED_MARK = 'DOC_EMERGANCY_RECEIVED_MARK',
    DOC_EMERGANCY_REQUEST_RECEIVED = 'DOC_EMERGANCY_REQUEST_RECEIVED';

export const SET_RECEPTION_ISSTART = 'SET_RECEPTION_ISSTART',
    SET_BEGIN_TIME = 'SET_BEGIN_TIME',
    SET_RECEPTION_ISCOMPLETE = 'SET_RECEPTION_ISCOMPLETE',
    SET_RECEPTION_ISTRIAL = 'SET_RECEPTION_ISTRIAL',
    SET_RECEPTION_ISCALLING = 'SET_RECEPTION_ISCALLING',
    SET_CHAT_FROM_ID = 'SET_CHAT_FROM_ID',
    SET_CHAT_TO_ID = 'SET_CHAT_TO_ID',
    SET_CHAT_TRAINING_ID = 'SET_CHAT_TRAINING_ID',
    SET_CHAT_STORY = 'SET_CHAT_STORY',
    SET_CONVERSATION_MODE = 'SET_CONVERSATION_MODE',
    SET_NEW_TIMER = 'SET_NEW_TIMER',
    SET_CHAT_INTERLOCUTOR_INFO = 'SET_CHAT_INTERLOCUTOR_INFO',
    SET_INTERLOCUTOR_STATUS = 'SET_INTERLOCUTOR_STATUS',
    SET_WEBSOCKET_STATUS = 'SET_WEBSOCKET_STATUS';


export const SET_FREE_INTERVALS = 'SET_FREE_INTERVALS', // abonement
    GET_SUBSCRIPTION_FOR_DISCIPLINE = 'GET_SUBSCRIPTION_FOR_DISCIPLINE',
    GET_STUDENT_BALANCE = 'GET_STUDENT_BALANCE',
    IS_PUSH_BTN_UNFRESH = 'IS_PUSH_BTN_UNFRESH',
    SET_NEED_SAVE_INTERVALS = 'SET_NEED_SAVE_INTERVALS',
    GET_USER_FONO = 'GET_USER_FONO',
    CHANGE_PUSH_BTN_UNFRESH = 'CHANGE_PUSH_BTN_UNFRESH';

export const CREATE_ABONEMENT = 'CREATE_ABONEMENT',
    GET_ABONEMENTS = 'GET_ABONEMENTS',
    CHANGE_CURRENT_DISCIPLINE = 'CHANGE_CURRENT_DISCIPLINE',
    SET_WEEK_INTERVAL = 'SET_WEEK_INTERVAL',
    SET_CHOOSE_THE_MASTER_BY_STUDENT = 'SET_CHOOSE_THE_MASTER_BY_STUDENT',
  
    GET_ABONEMENTS2 = 'GET_ABONEMENTS2';

export const  // student
    HANDLE_SELECTING='HANDLE_SELECTING',

    GET_DEADLINE_PAY = 'GET_DEADLINE_PAY',
    GET_FULL_INFO_MASTERS = 'GET_FULL_INFO_MASTERS',
    GET_THE_MASTER_INTERVAL = 'GET_THE_MASTER_INTERVAL',
    UNSET_IS_PUSH_BTN_TRANSFER = 'UNSET_IS_PUSH_BTN_TRANSFER',
    CHANGE_BTN_BACK = 'CHANGE_BTN_BACK',
    CHANGE_PUSH_BTN_TRANSFER = 'CHANGE_PUSH_BTN_TRANSFER',

    SET_WEEKDAYS_AND_DISCIPLINE_AND_ARRMASTERS = 'SET_WEEKDAYS_AND_DISCIPLINE_AND_ARRMASTERS',

    GET_AVAILABLE_INTERVAL = 'GET_AVAILABLE_INTERVAL',
    GET_TRAINING_TRIAL_STATUS = 'GET_TRAINING_TRIAL_STATUS',
    SET_TRAININGS_AVAILABLE_STATUS = 'SET_TRAININGS_AVAILABLE_STATUS',
    RESET_TRAININGS_TRIAL_STATUS = 'RESET_TRAININGS_TRIAL_STATUS',
    MASTER_SCHEDULE = 'MASTER_SCHEDULE',
    SET_TRANSFER_TRAIN_MODAL_INACTIVE = 'SET_TRANSFER_TRAIN_MODAL_INACTIVE',
    SET_IS_PUSH_BTN_TRANSFER = 'SET_IS_PUSH_BTN_TRANSFER',
    SET_IS_PUSH_BTN_ADD = 'SET_IS_PUSH_BTN_ADD',
    SET_IS_PUSH_TRIAL_TRAINING = 'SET_IS_PUSH_TRIAL_TRAINING',
    SET_NO_PUSH_BTN = 'SET_NO_PUSH_BTN',
    GET_DISCIPLINE_COMMUNICATION = 'GET_DISCIPLINE_COMMUNICATION',
    SET_MASTER_THE_DISCIPLINE = 'SET_MASTER_THE_DISCIPLINE',
    SET_DISC_ABONEMENT = 'SET_DISC_ABONEMENT',
    GET_USE_FROZEN_TRAINING = 'GET_USE_FROZEN_TRAINING',
    GET_USER_INFO = 'GET_USER_INFO';

export const GET_MASTER_LIST = 'GET_MASTER_LIST',
    SET_CHOOSE_MASTER = 'SET_CHOOSE_MASTER',
    GET_POST_TRAINER_TRAINING = 'GET_POST_TRAINER_TRAINING',
    GET_FUTURE_TRAINER_TRAINING = 'GET_FUTURE_TRAINER_TRAINING',
    GET_TODAY_TRAINER_TRAINING = 'GET_TODAY_TRAINER_TRAINING',
    GET_TRAINER_TRAINING_BY_TRAINER = 'GET_TRAINER_TRAINING_BY_TRAINER',
    GET_MASTER_LIST_OBJ = 'GET_MASTER_LIST_OBJ',
    GET_TRAINER_TRAINING = 'GET_TRAINER_TRAINING'; // coach


export const 
    HANDLE_CHANGE_TIME = 'HANDLE_CHANGE_TIME',
    GET_NEXT_TRAINING = 'GET_NEXT_TRAINING',
    GET_MY_MASTERS_OR_STUDENTS = 'GET_MY_MASTERS_OR_STUDENTS',
    UNAUTHORIZED_TRIAL_DATA = 'UNAUTHORIZED_TRIAL_DATA',
    GET_ALL_STUDENT_TRAININGS = 'GET_ALL_STUDENT_TRAININGS',
    GET_TRIAL_FUTURE_TRAINING = 'GET_TRIAL_FUTURE_TRAINING',
    GET_COUNT_TRAINING_BY_DISCIPLINE = 'GET_COUNT_TRAINING_BY_DISCIPLINE',
    SAVE_NOTIFICATION = 'SAVE_NOTIFICATION',
    IS_SET_TRIAL = 'IS_SET_TRIAL',
    GET_TRAINING_NOT_FINISHED = 'GET_TRAINING_NOT_FINISHED'; //training

//admin
export const GET_FREE_AND_BUSY_MASTER_LIST = 'GET_FREE_AND_BUSY_MASTER_LIST', 
    //GET_ALL_ADMIN_INFO_MASTERS_BUSY = 'GET_ALL_ADMIN_INFO_MASTERS_BUSY',
    //GET_ALL_ADMIN_INFO_MASTERS_FREE = 'GET_ALL_ADMIN_INFO_MASTERS_FREE',
    GET_REPORT_REGISTRATION_LINKS = 'GET_REPORT_REGISTRATION_LINKS',
    INFO_SCHEDULE_STUDENT = 'INFO_SCHEDULE_STUDENT',
    GET_REPORT_LINKS = 'GET_REPORT_LINKS',
    
    GET_FREE_AND_BUSY_MASTER_LIST_ON_HOUR = 'GET_FREE_AND_BUSY_MASTER_LIST_ON_HOUR';

export const GET_TOKEN = 'GET_TOKEN',
    CHECK_TOKEN = 'CHECK_TOKEN';

export const GET_TRAINING_HISTORY_LIST_SUCCESS = 'GET_TRAINING_HISTORY_LIST_SUCCESS',
    GET_TRAINING_HISTORY_LIST_FAILED = 'GET_TRAINING_HISTORY_LIST_FAILED',
    SET_LOADING_STATUS = 'SET_LOADING_STATUS',
    CHANGE_MAX_AMOUNT = 'CHANGE_MAX_AMOUNT',
    RESET_TRAINING_HISTORY_LIST = 'RESET_TRAINING_HISTORY_LIST';


//new schedule
export const GET_STUDENTS_SCHEDULE = 'GET_STUDENTS_SCHEDULE';

//modal
export const SHOW_LIST_TRAINERS_MODAL = 'SHOW_LIST_TRAINERS_MODAL',
    HIDE_LIST_TRAINERS_MODAL = 'HIDE_LIST_TRAINERS_MODAL',
    
    SHOW_TRANSFER_OR_FREEZE_MODAL = 'SHOW_TRANSFER_OR_FREEZE_MODAL',
    HIDE_TRANSFER_OR_FREEZE_MODAL = 'HIDE_TRANSFER_OR_FREEZE_MODAL',
    
    SHOW_CREATE_TRAIN_MODAL_CLICK_UNFREEZE='SHOW_CREATE_TRAIN_MODAL_CLICK_UNFREEZE',
    HIDE_CREATE_TRAIN_MODAL_CLICK_UNFREEZE='HIDE_CREATE_TRAIN_MODAL_CLICK_UNFREEZE',
    SHOW_CREATE_TRAIN_MODAL_CLICK_TRIAL='SHOW_CREATE_TRAIN_MODAL_CLICK_TRIAL',
    HIDE_CREATE_TRAIN_MODAL_CLICK_TRIAL='HIDE_CREATE_TRAIN_MODAL_CLICK_TRIAL';

//schedule
export const SET_PARAMS_ID = 'SET_PARAMS_ID';
